namespace RefDocGen.IntegrationTests.Tools;
// this file was generated by ChatGPT

/// <summary>
/// Represents a <c>data-id</c> attribute present in the resulting documentation
/// </summary>
internal enum DataId
{
    MemberDeclaration,
    AttributeData,
    ReturnTypeName,
    ParameterElement,
    ParameterDeclaration,
    ParameterDoc,
    TypeParameterElement,
    TypeParameterDeclaration,
    TypeParameterDoc,
    SummaryDoc,
    RemarksDoc,
    ReturnsDoc,
    ValueDoc,
    SeeAlsoDocs,
    TypeParamConstraints,
    BaseType,
    ImplementedInterfaces,
    TypeNamespace,
    TypeAssembly,
    DeclaringType,
    ExceptionData,
    ExceptionType,
    ExceptionDoc,
    DelegateMethod,
    NamespaceClasses,
    NamespaceInterfaces,
    NamespaceDelegates,
    NamespaceEnums,
    NamespaceStructs,
    TypeRowElement,
    TypeRowName,
    TypeRowDoc,
    NamespaceName,
    TypeDeclaration,
    TypeDataSection,
    NestedTypeData,
    NestedTypeName,
    MemberInheritedFrom,
    MemberOverrides,
    MemberExplicitlyImplements,
    MemberImplements,
    PageBody,
    AttributesSection
}

/// <summary>
/// Class containing extension methods for <see cref="DataId"/> enum.
/// </summary>
internal static class DataIdExtensions
{
    /// <summary>
    /// Gets a string representation of the provided <see cref="DataId"/>.
    /// </summary>
    /// <param name="dataId">The provided <see cref="DataId"/>.</param>
    /// <returns>String representation of the provided <see cref="DataId"/>.</returns>
    internal static string GetString(this DataId dataId)
    {
        return dataId switch
        {
            DataId.MemberDeclaration => "member-declaration",
            DataId.AttributeData => "attribute-data",
            DataId.ReturnTypeName => "return-type-name",
            DataId.ParameterElement => "parameter-data",
            DataId.ParameterDeclaration => "parameter-declaration",
            DataId.ParameterDoc => "parameter-doc",
            DataId.TypeParameterElement => "type-parameter-data",
            DataId.TypeParameterDeclaration => "type-parameter-declaration",
            DataId.TypeParameterDoc => "type-parameter-doc",
            DataId.SummaryDoc => "summary-doc",
            DataId.RemarksDoc => "remarks-doc",
            DataId.ReturnsDoc => "returns-doc",
            DataId.ValueDoc => "value-doc",
            DataId.SeeAlsoDocs => "seealso-item",
            DataId.TypeParamConstraints => "type-param-constraints",
            DataId.BaseType => "base-type",
            DataId.ImplementedInterfaces => "implemented-interfaces",
            DataId.TypeNamespace => "type-namespace",
            DataId.ExceptionData => "exception-data",
            DataId.ExceptionType => "exception-type",
            DataId.ExceptionDoc => "exception-doc",
            DataId.DelegateMethod => "delegate-method",
            DataId.NamespaceClasses => "namespace-classes",
            DataId.NamespaceInterfaces => "namespace-interfaces",
            DataId.NamespaceDelegates => "namespace-delegates",
            DataId.NamespaceEnums => "namespace-enums",
            DataId.NamespaceStructs => "namespace-structs",
            DataId.TypeRowElement => "type-row-element",
            DataId.TypeRowName => "type-row-name",
            DataId.TypeRowDoc => "type-row-doc",
            DataId.NamespaceName => "namespace-name",
            DataId.TypeDeclaration => "type-declaration",
            DataId.TypeDataSection => "declared-type-data",
            DataId.DeclaringType => "declaring-type",
            DataId.NestedTypeData => "nested-type-data",
            DataId.NestedTypeName => "nested-type-name",
            DataId.MemberInheritedFrom => "member-inherited-from",
            DataId.MemberOverrides => "member-overrides",
            DataId.MemberExplicitlyImplements => "member-explicitly-implements",
            DataId.MemberImplements => "member-implements",
            DataId.PageBody => "page-body",
            DataId.TypeAssembly => "type-assembly",
            DataId.AttributesSection => "attributes-section",
            _ => throw new ArgumentException($"The provided DataId '{dataId}' has no string representation.")
        };
    }
}
