using RefDocGen.CodeElements.Abstract;
using RefDocGen.CodeElements.Abstract.Types;
using RefDocGen.CodeElements.Concrete;
using RefDocGen.CodeElements.Concrete.Types;
using RefDocGen.CodeElements.Concrete.Types.Delegate;
using RefDocGen.CodeElements.Concrete.Types.Enum;
using RefDocGen.DocExtraction.Tools;
using RefDocGen.TemplateGenerators.Tools.TypeName;
using RefDocGen.Tools.Xml;
using System.Xml.Linq;

namespace RefDocGen.TemplateGenerators.Tools;

internal interface IDocCommentParser
{
    string ToHtmlString(XElement docComment);
}

internal abstract class DefaultDocCommentParser : IDocCommentParser
{

    /// <summary>
    /// Marks the <paramref name="element"/> and all of its child elements as generated by the app.
    /// </summary>
    /// <param name="element"></param>
    /// <returns></returns>
    private XElement MarkAsGenerated(XElement element)
    {
        var attribute = new XAttribute("refdocgen-generated", true);

        element.Add(attribute);

        foreach (var e in element.Elements())
        {
            _ = MarkAsGenerated(e);
        }

        return new XElement(element);
    }

    private XElement Transform(XElement before, XElement template)
    {
        var newElement = MarkAsGenerated(template);

        var deepestChild = newElement.GetEmptyDescendantOrSelf();
        deepestChild.Add(before.Nodes());

        return newElement;
    }

    private XElement Transform(XElement before, XElement template, string attribute)
    {
        var newElement = MarkAsGenerated(template);

        var deepestChild = newElement.GetEmptyDescendantOrSelf();
        deepestChild.Add(before.Nodes());

        if (before.Attribute(attribute) is XAttribute attr && !before.Nodes().Any())
        {
            deepestChild.Add(attr.Value);
        }

        return newElement;
    }

    private void CustomReplace(XElement node1, XElement node2)
    {
        if (node1 == node2)
        {
            return;
        }

        node1.Name = node2.Name;
        node1.ReplaceAttributes(node2.Attributes());
        node1.ReplaceNodes(node2.Nodes());
    }

    protected readonly ITypeRegistry typeRegistry;

    protected virtual XElement ParagraphElement => new("div");

    protected virtual XElement BulletListElement => new("ul");

    protected virtual XElement NumberListElement => new("ol");

    protected virtual XElement ListItemElement => new("li");

    protected virtual XElement InlineCodeElement => new("code");

    protected virtual XElement CodeBlockElement => new("pre",
                                                        new XElement("code")
                                                    );

    protected virtual XElement ExampleElement => new("div");

    protected virtual XElement ParamRefElement => new("xxx");

    protected virtual XElement TypeParamRefElement => new("code");

    protected virtual XElement SeeCrefElement => new("a");

    protected virtual XElement SeeHrefElement => new("a");

    protected virtual XElement SeeLangwordElement => new("code");

    protected virtual XElement SeeCrefNotFoundElement => new("code");

    protected virtual XElement SeeAlsoCrefElement => new("a");

    protected virtual XElement SeeAlsoHrefElement => new("a");

    protected virtual XElement SeeAlsoNotFoundElement => new("code");

    private readonly string[] toRemove = ["summary", "remarks", "returns", "exception", "value"];

    protected DefaultDocCommentParser(ITypeRegistry typeRegistry)
    {
        this.typeRegistry = typeRegistry;
    }

    protected DefaultDocCommentParser() // TODO: code smell
    {
        typeRegistry = new TypeRegistry(
                new Dictionary<string, ObjectTypeData>(),
                new Dictionary<string, EnumTypeData>(),
                new Dictionary<string, DelegateTypeData>()
            );
    }

    public string ToHtmlString(XElement docComment)
    {
        var docCommentCopy = new XElement(docComment);
        TransformToHtml(docCommentCopy);

        return docCommentCopy.ToString();
    }

    private void TransformToHtml(XElement element)
    {
        var transformedElement = element;

        if (element.Attribute("refdocgen-generated") is null)
        {
            if (element.Name == "para")
            {
                transformedElement = TransformParagraphElement(element);
            }
            else if (element.Name == "list")
            {
                transformedElement = TransformListElement(element);
            }
            else if (element.Name == "item")
            {
                transformedElement = TransformListItemElement(element);
            }
            else if (element.Name == "c")
            {
                transformedElement = TransformInlineCodeElement(element);
            }
            else if (element.Name == "code")
            {
                transformedElement = TransformCodeBlockElement(element);
            }
            else if (element.Name == "example")
            {
                transformedElement = TransformExampleElement(element);
            }
            else if (element.Name == "see")
            {
                transformedElement = TransformSeeElement(element);
            }
            else if (element.Name == "seealso")
            {
                transformedElement = TransformSeeElement(element); // TODO: add
            }
            else if (element.Name == "paramref")
            {
                transformedElement = TransformParamRefElement(element);
            }
            else if (element.Name == "typeparamref")
            {
                transformedElement = TransformTypeParamRefElement(element);
            }
            else if (toRemove.Contains(element.Name.LocalName))
            {
                element.Name = "div";
                transformedElement = element;
            }
        }

        CustomReplace(element, transformedElement);

        foreach (var child in element.Elements())
        {
            TransformToHtml(child);
        }
    }

    protected virtual XElement TransformListElement(XElement element)
    {
        string listType = element.Attribute("type")?.Value ?? "bullet";

        var types = new Dictionary<string, XElement>()
        {
            ["bullet"] = BulletListElement,
            ["number"] = NumberListElement,
            ["table"] = BulletListElement, // TODO: add 
        };

        return types.TryGetValue(listType, out var newElement)
            ? Transform(element, newElement)
            : element;
    }

    protected virtual XElement TransformListItemElement(XElement element)
    {
        return Transform(element, ListItemElement);
    }

    protected virtual XElement TransformParagraphElement(XElement element)
    {
        return Transform(element, ParagraphElement);
    }

    protected virtual XElement TransformInlineCodeElement(XElement element)
    {
        return Transform(element, InlineCodeElement);
    }

    protected virtual XElement TransformCodeBlockElement(XElement element)
    {
        return Transform(element, CodeBlockElement);
    }

    protected virtual XElement TransformExampleElement(XElement element)
    {
        return Transform(element, ExampleElement);
    }

    protected virtual XElement TransformSeeElement(XElement element)
    {
        if (element.Attribute(XmlDocIdentifiers.Href) is XAttribute hrefAttr)
        {
            return TransformAnySeeHrefElement(element, hrefAttr.Value);
        }
        else if (element.Attribute(XmlDocIdentifiers.Cref) is XAttribute crefAttr)
        {
            return TransformAnySeeCrefElement(element, crefAttr.Value);
        }
        else if (element.Attribute(XmlDocIdentifiers.Langword) is XAttribute langwordAttr)
        {
            return TransformAnySeeLangwordElement(element, langwordAttr.Value);
        }
        else
        {
            return element;
        }
    }

    protected virtual XElement TransformAnySeeHrefElement(XElement element, string hrefValue)
    {
        var newElement = MarkAsGenerated(SeeHrefElement);
        var deepestChild = newElement.GetEmptyDescendantOrSelf();

        if (element.Nodes().Any())
        {
            deepestChild.Add(element.Nodes());
        }
        else
        {
            deepestChild.Add(hrefValue);
        }

        deepestChild.Add(
            new XAttribute(XmlDocIdentifiers.Href, hrefValue)
            );

        return newElement;
    }

    protected virtual XElement TransformAnySeeLangwordElement(XElement element, string langword)
    {
        return Transform(element, SeeLangwordElement, XmlDocIdentifiers.Langword);
    }

    protected virtual XElement TransformAnySeeCrefElement(XElement element, string crefValue)
    {
        string[] splitMemberName = crefValue.Split(':');
        (string objectIdentifier, string fullObjectName) = (splitMemberName[0], splitMemberName[1]);

        string typeId;
        string? memberId = null;

        if (objectIdentifier == MemberTypeId.Type) // type
        {
            typeId = fullObjectName;
        }
        else if (objectIdentifier == "!") // reference not found
        {
            return TransformNotFoundCrefElement(element, fullObjectName);
        }
        else // member
        {
            (typeId, string memberName, string paramsString) = MemberSignatureParser.Parse(fullObjectName);
            memberId = memberName + paramsString;
        }

        // type found
        if (typeRegistry.GetDeclaredType(typeId) is ITypeDeclaration type)
        {
            var newElement = MarkAsGenerated(SeeCrefElement);
            var deepestChild = newElement.GetEmptyDescendantOrSelf();

            string target = typeId + ".html";
            string targetName = CSharpTypeName.Of(type);

            // TODO: check if member is found

            if (memberId is not null)
            {
                target += $"#{memberId}";
                targetName += $".{memberId}";
            }

            deepestChild.Add(
                new XAttribute(XmlDocIdentifiers.Href, target)
            );

            // no child nodes -> add cref 
            if (!element.Nodes().Any())
            {
                deepestChild.Add(targetName);
            }
            else
            {
                deepestChild.Add(element.Nodes());
            }

            return newElement;
        }
        else // type not found
        {
            var newElement = MarkAsGenerated(SeeAlsoNotFoundElement);
            var deepestChild = newElement.GetEmptyDescendantOrSelf();

            deepestChild.Add();

            if (!element.Nodes().Any())
            {
                deepestChild.Add(new XText(fullObjectName));
            }
            else
            {
                deepestChild.Add(element.Nodes());
            }

            return newElement;
        }
    }

    protected virtual XElement TransformNotFoundCrefElement(XElement element, string crefValue)
    {
        return Transform(element, SeeCrefNotFoundElement, XmlDocIdentifiers.Cref);
    }

    protected virtual XElement TransformParamRefElement(XElement element)
    {
        return TransformAnyParamRefElement(element, ParamRefElement);
    }

    protected virtual XElement TransformTypeParamRefElement(XElement element)
    {
        return TransformAnyParamRefElement(element, TypeParamRefElement);
    }

    protected virtual XElement TransformAnyParamRefElement(XElement element, XElement htmlElement)
    {
        return Transform(element, htmlElement, XmlDocIdentifiers.Name);
    }
}

internal class CustomDocCommentParser : DefaultDocCommentParser
{
    public CustomDocCommentParser()
    {
    }

    public CustomDocCommentParser(ITypeRegistry typeRegistry) : base(typeRegistry)
    {
    }

    protected override XElement ParamRefElement =>
        new(
            "code",
            new XAttribute("class", "text-warning bg-success")); // TODO: just for demo, remove afterwards
}
