// This file was generated by ChatGPT

namespace RefDocGen.Tools.Xml;

/// <summary>
/// Contains constants representing XML element and attribute names found in XML doc comments.
/// </summary>
internal static class XmlDocIdentifiers
{
    /// <summary>
    /// Represents the 'member' identifier.
    /// </summary>
    public const string Member = "member";

    /// <summary>
    /// Represents the 'summary' identifier.
    /// </summary>
    public const string Summary = "summary";

    /// <summary>
    /// Represents the 'name' identifier.
    /// </summary>
    public const string Name = "name";

    /// <summary>
    /// Represents the 'param' identifier.
    /// </summary>
    public const string Param = "param";

    /// <summary>
    /// Represents the 'typeparam' identifier.
    /// </summary>
    public const string TypeParam = "typeparam";

    /// <summary>
    /// Represents the 'returns' identifier.
    /// </summary>
    public const string Returns = "returns";

    /// <summary>
    /// Represents the 'value' identifier.
    /// </summary>
    public const string Value = "value";

    /// <summary>
    /// Represents the 'remarks' identifier.
    /// </summary>
    public const string Remarks = "remarks";

    /// <summary>
    /// Represents the 'exception' identifier.
    /// </summary>
    public const string Exception = "exception";

    /// <summary>
    /// Represents the 'cref' identifier.
    /// </summary>
    public const string Cref = "cref";

    /// <summary>
    /// Represents the 'href' identifier.
    /// </summary>
    public const string Href = "href";

    /// <summary>
    /// Represents the 'langword' identifier.
    /// </summary>
    public const string Langword = "langword";

    /// <summary>
    /// Represents the 'inheritdoc' identifier.
    /// </summary>
    public const string InheritDoc = "inheritdoc";

    /// <summary>
    /// Represents the 'seealso' identifier.
    /// </summary>
    public const string SeeAlso = "seealso";

    /// <summary>
    /// Represents the 'path' identifier.
    /// </summary>
    public const string Path = "path";

    /// <summary>
    /// Represents the 'para' identifier.
    /// </summary>
    public const string Para = "para";

    /// <summary>
    /// Represents the 'list' identifier.
    /// </summary>
    public const string List = "list";

    /// <summary>
    /// Represents the 'item' identifier.
    /// </summary>
    public const string Item = "item";

    /// <summary>
    /// Represents the 'term' identifier.
    /// </summary>
    public const string Term = "term";

    /// <summary>
    /// Represents the 'description' identifier.
    /// </summary>
    public const string Description = "description";

    /// <summary>
    /// Represents the 'description' identifier.
    /// </summary>
    public const string ListHeader = "listheader";

    /// <summary>
    /// Represents the 'c' identifier.
    /// </summary>
    public const string InlineCode = "c";

    /// <summary>
    /// Represents the 'code' identifier.
    /// </summary>
    public const string CodeBlock = "code";

    /// <summary>
    /// Represents the 'example' identifier.
    /// </summary>
    public const string Example = "example";

    /// <summary>
    /// Represents the 'see' identifier.
    /// </summary>
    public const string See = "see";

    /// <summary>
    /// Represents the 'paramref' identifier.
    /// </summary>
    public const string ParamRef = "paramref";

    /// <summary>
    /// Represents the 'typeparamref' identifier.
    /// </summary>
    public const string TypeParamRef = "typeparamref";
}
