using System.Reflection;
using System.Runtime.CompilerServices;

namespace RefDocGen.AssemblyAnalysis.Extensions;

/// <summary>
/// Class containing extension methods for <see cref="MemberInfo"/> class and its subclasses.
/// </summary>
internal static class MemberInfoExtensions
{
    /// <summary>
    /// Checks whether the member is generated by a compiler (true for e.g. get_* set_* property methods).
    /// </summary>
    /// <param name="memberInfo">The member to check.</param>
    /// <returns><c>true</c> if the member is generated by the compiler; otherwise, <c>false</c>.</returns>
    internal static bool IsCompilerGenerated(this MemberInfo memberInfo)
    {
        return memberInfo.GetCustomAttribute<CompilerGeneratedAttribute>() is not null;
    }

    /// <summary>
    /// Checks whether the <see cref="MethodInfo"/> object represents an operator or not.
    /// </summary>
    /// <param name="methodInfo">The <see cref="MethodInfo"/> to check.</param>
    /// <returns><c>true</c> if the <see cref="MethodInfo"/> represents an operator; <c>false</c> otherwise.</returns>
    internal static bool IsOperator(this MethodInfo methodInfo)
    {
        return methodInfo.IsSpecialName && methodInfo.Name.StartsWith("op_", StringComparison.InvariantCulture);
    }

    /// <summary>
    /// Checks whether the given <see cref="Type"/> represents an delegate or not.
    /// </summary>
    /// <param name="type">The <see cref="Type"/> to check.</param>
    /// <returns><c>true</c> if the <see cref="Type"/> represents an delegate; <c>false</c> otherwise.</returns>
    internal static bool IsDelegate(this Type type)
    {
        return typeof(MulticastDelegate).IsAssignableFrom(type) && type != typeof(MulticastDelegate);
    }

    /// <summary>
    /// Checks whether the given <see cref="PropertyInfo"/> represents an indexer or not.
    /// </summary>
    /// <param name="property">The <see cref="PropertyInfo"/> to check.</param>
    /// <returns><c>true</c> if the <see cref="PropertyInfo"/> represents an indexer; <c>false</c> otherwise.</returns>
    internal static bool IsIndexer(this PropertyInfo property)
    {
        return property.GetIndexParameters().Length > 0;
    }
}
