using System.Reflection;
using System.Runtime.InteropServices;

namespace RefDocGen.AssemblyAnalysis;

/// <summary>
/// Class containing extension methods for <see cref="CustomAttributeData"/> class.
/// </summary>
internal static class CustomAttributeDataExtensions
{
    /// <summary>
    /// Checks whether the attribute is generated by a compiler.
    /// </summary>
    /// <param name="attribute">The attribute to check.</param>
    /// <returns><c>true</c> if the attribute is generated by the compiler; otherwise, <c>false</c>.</returns>
    internal static bool IsCompilerGenerated(this CustomAttributeData attribute)
    {
        string[] excludedNamespaces = [
            "System.Runtime.CompilerServices",
            "System.Diagnostics"]; // exclude attributes for internal usage

        Type[] excludedTypes = [
            typeof(InAttribute),
            typeof(OutAttribute),
            typeof(ParamArrayAttribute),
            typeof(OptionalAttribute)]; // exclude specific parameter-related attributes

        return excludedNamespaces.Contains(attribute.AttributeType.Namespace) || excludedTypes.Contains(attribute.AttributeType);
    }
}
